abstract: XMLRPC interface to xmms2
author: Florian Ragwitz, C<< <rafl at debian.org> >>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Audio-XMMSClient-XMLRPC
no_index: 
  directory: 
    - inc
    - t
requires: 
  Audio::XMMSClient: 0
  RPC::XML: 0
version: 0.03
