# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Audio-XMMSClient-XMLRPC
version:      0.02
version_from: lib/Audio/XMMSClient/XMLRPC.pm
installdirs:  site
requires:
    Audio::XMMSClient:             0
    RPC::XML:                      0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
